# Configuração simples do H2 gravando em arquivo local
spring.datasource.url=jdbc:h2:file:./data/estoquedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite que o JPA crie as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update